#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Souma Nomoto
# SPDX-License-Indentifier: BSD-3-Clause
import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += int(line)
    except:    
        ans += float(line)
    

print(ans)
